// Quiz Questions Array
var questions = [
    {
        question: "What method returns a strings value as all uppercase characters?",
        a: "toUpper()",
        b: "toUpperCase()",
        c: "changeCaseType()",
        d: "UpperCase()",
        correct: "b",
    },
    {
        question: "What data type only has the 2 values of true or false",
        a: "Boolean",
        b: "String",
        c: "Number",
        d: "Null",
        correct: "a",
    },
    {
        question: "Which data type is not a primitive type?",
        a: "String",
        b: "Number",
        c: "Object",
        d: "Boolean",
        correct: "c",
    },
    {
        question: "Which comparison operator is used to compare both value and type?",
        a: "==",
        b: "<=",
        c: "!=",
        d: "===",
        correct: "d",
    },
    {
        question: "What is an example of camelCase?",
        a: "MyVariable",
        b: "myVariable",
        c: "MyVaRiAbLe",
        d: "MYVARIABLE",
        correct: "b",
    },
    {
        question: "What is the correct syntax for linking an external script file to the HTML",
        a: "<script href='script.js'>",
        b: "<script src='script.js'>",
        c: "<script name='script.js'>",
        d: "<script='script.js'>",
        correct: "b",
    },
];
